name: DotX
main: co.dotarch.x.plugin.DotX
version: 0.3.2.4
api-version: 1.21
load: STARTUP
depend: [PlaceholderAPI]
commands:
  dotapi:
    description: Information about DotAPI
    permission: dotapi
    usage: "§cUsage: /<command>"
  vconfig:
    description: VConfig options
    permission: dotapi.vconfig
    usage: "§cUsage: /<command>"
  dotblock:
    description: Get dot block
    permission: dotapi.dotblock
    usage: "§cUsage: /<command> <material> <class>"