name: DotX
main: co.dotarch.x.plugin.DotX
version: 0.0.0.4
api-version: 1.21
load: startup
depend: [PlaceholderAPI]
commands:
  dotapi:
    description: Information about DotAPI
    permission: dotapi
    usage: "§cUsage: /<command>"
  vconfig:
    description: VConfig options
    permission: dotapi.vconfig
    usage: "§cUsage: /<command>"